# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 127

  # include test files or not, default is true
  tests: true

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  # modules-download-mode: vendor

# all available settings of specific linters
linters-settings:
  gci:
    # put imports beginning with prefix after 3rd-party packages;
    # only support one prefix
    # if not set, use goimports.local-prefixes
    local-prefixes: github.com/wcharcuzk/go-diskq

  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/wcharcuzk/go-diskq

  revive:
    severity: warning

  govet:
    # report about shadowed variables
    check-shadowing: false

  staticcheck:
    # checks: [S1000,S1008,S1023,S1035,SA4006,SA5008]
    checks: ["all"]

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US

linters:
  enable:
    - gofmt
    - govet
    - godot
    - revive
    - ineffassign
    - errcheck
    - misspell
    - unused
    - unparam
    - prealloc
  fast: true
